### ISSUE TITLE
Use `𝒊, 𝒋, 𝒌` as symbols of the basis of `Quaternion`?

### ISSUE THREAD

**Issue by hyrodium** [JuliaGeometry/Quaternions.jl#50]
We can define symbols for basis of `Quaternion` like [`im`](https://github.com/JuliaLang/julia/blob/master/base/complex.jl#L36).
```julia
const 𝒊 = Quaternion(false,true,false,false,true)  # type \bii in REPL
const 𝒋 = Quaternion(false,false,true,false,true)  # type \bij in REPL
const 𝒌 = Quaternion(false,false,false,true,true)  # type \bik in REPL
```
Additionally, we can add `Base.show(io::IO, q::Quaternion)` method to show the quaternion in REPL.

Is this sounds great? If so, I'll make a PR.

**Comment by sethaxen** [comment]
Personally I dislike this. I suspect users will need to look for and copy-paste these symbols to use them, and then, constructing quaternions this way instead of with the constructor could be wasteful.

**Comment by hyrodium** [comment]
>I suspect users will need to look for and copy-paste these symbols to use them,

I agree with that. Users can *learn* how to input the characters in REPL, but copy&paste is required.

```julia
help?> 𝒊
"𝒊" can be typed by \bii<tab>
```

I don’t think the characters `𝒊, 𝒋, 𝒌` are the best choice, so I don’t care much. (`im_i, im_j, im_k` seems verbose.)

What I was concerned is the output in REPL.
```julia
julia> Quaternion(1,2,3,4)
Quaternion{Int64}(1, 2, 3, 4, false)
```
Some packages use quaternion w+ix+jy+kz with order `(x,y,z,w)` instead of `(w,x,y,z)`. See https://github.com/JuliaPlots/Makie.jl/blob/master/src/utilities/quaternions.jl#L23 for example.
So, I thought it's better to clarify what the real part is.

>constructing quaternions this way instead of with the constructor could be wasteful.

It seems we already have the same thing with `Base.im`. I thought it's better to follow the `Base`, and addling [well-documentation like this](https://docs.julialang.org/en/v1/manual/complex-and-rational-numbers/#Complex-Numbers) will be great.

>However, this is not recommended. Instead, use the more efficient [complex](https://docs.julialang.org/en/v1/base/numbers/#Base.complex-Tuple{Complex}) function to construct a complex value directly from its real and imaginary parts:

**Comment by sethaxen** [comment]
Yeah, the Base docs indicate that `im` is convenient syntactic sugar that is probably best used for convenience in the REPL or for defining constants in the code but in general should not be used. `complex` should be the preferred way to do things, and I think we should have the same convention regarding `quat`, `octo`, etc.

Personally I prefer the current `show` methods for several reasons:
1. they're valid constructors. If we had an `ijk` show method for quaternions, the user might expect that they can construct the quaternion that way or that this is recommended, when it would not be.
2. they're consistent across quaternions, dual quaternions, and octonions. If we added a custom `ijk` style show method for quaternions, then this would be inconsistent, and then we would be in the place of needing to add even more constants to support octonions, which should use different constants, and dual quaternions,
3. while other implementations may put the real part last, users of this package should expect to read and use our API. Also, putting the real part first would be consistent across all hypercomplex numbers, so I don't see why we should add more specialized (and ultimately less useful, due to the above points) show methods to avoid this.

> It seems we already have the same thing with `Base.im`. I thought it's better to follow the `Base`, and addling [well-documentation like this](https://docs.julialang.org/en/v1/manual/complex-and-rational-numbers/#Complex-Numbers) will be great.

Base needs this documentation precisely because they do include an `im` constant, so I don't think we need this documentation specifically. That being said, we should have documented constructors for `Quaternion`, etc, to make the order of arguments obvious, and actual package documentation (#44)

**Comment by sethaxen** [comment]
> What I was concerned is the output in REPL.
> 
> ```julia
> julia> Quaternion(1,2,3,4)
> Quaternion{Int64}(1, 2, 3, 4, false)
> ```
> 
> Some packages use quaternion w+ix+jy+kz with order `(x,y,z,w)` instead of `(w,x,y,z)`. See https://github.com/JuliaPlots/Makie.jl/blob/master/src/utilities/quaternions.jl#L23 for example. So, I thought it's better to clarify what the real part is.

Interestingly, this package already defines `show` methods. But because it neglected to import `Base.show`, they are not used. e.g.
https://github.com/JuliaGeometry/Quaternions.jl/blob/cbb1a07ca402641884ea92870ad063f1a22daef5/src/Quaternion.jl#L40-L43

According to the [ColPrac guide](https://github.com/SciML/ColPrac#changes-that-are-not-considered-breaking), changes to `show` methods are not breaking.

**Comment by hyrodium** [comment]
Sorry for forgetting to reply. I agree with all of your points, and this issue can be closed:smile:
